const yiiModelNames = ["Country","Respondent","RespondentMailingList","User"] as const;
const yiiModelAttributeNames = ["Country","Respondent","RespondentMailingList","User","RespondentMailingList.reml_comp_name","RespondentMailingList.reml_pers_joti","RespondentMailingList.reml_pers_name"] as const;
export type TYiiModelNames = typeof yiiModelNames[number];
export type TYiiModelAttributeNames = typeof yiiModelAttributeNames[number];
function attr(name: TYiiModelAttributeNames) { return name.split('.'); }
function name<GName extends TYiiModelNames>(name: GName): GName { return name; }
const yiiModelColumnSizes = {"Menu.menu_name":60,"RbacRole.role_desc":200,"RbacRole.role_name":150,"RbacRoute.rout_ctrl_name":40,"RbacRoute.rout_ctrl_path":100,"RbacRoute.rout_name":100,"RbacRoute.rout_path":100,"User.user_cpf":18,"User.user_mail":50,"User.user_name":60,"User.user_pass":80,"UserToken.ustk_mail":50,"UserToken.ustk_toke":255,"Question.ques_desc":800,"QuestionCategory.quca_name":60,"QuestionOption.quop_desc":800,"Quiz.quiz_name":200,"Quiz.quiz_titl":60,"Template.tplt_name":100,"TemplateQuestion.tpqu_desc":800,"Respondent.aux_company_name":200,"Respondent.aux_person_name":60,"Respondent.resp_mail":50,"RespondentMailingList.reml_comp_name":100,"RespondentMailingList.reml_pers_joti":100,"RespondentMailingList.reml_pers_name":60,"Subject.subj_name":60,"City.city_coun":3,"City.city_ibge":18,"City.city_name":40,"City.city_name_ci":40,"City.city_stte_acro":2,"Country.coun_code":3,"Country.coun_iso2":6,"Country.coun_name":60,"Country.coun_name_ci":60,"Country.coun_name_en":60,"Country.coun_ncod":4,"File.file_mity":100,"File.file_name":800,"File.file_path":200,"Region.regi_name":20,"State.stte_acro":2,"State.stte_coun":3,"State.stte_name":40,"State.stte_vsca":18,"State.stte_vsca_pro2":18,"State.stte_vsca_prom":18,"State.stte_vsin":18,"State.stte_vsin_pro2":18,"State.stte_vsin_prom":18,"Type.type_cons":40,"Type.type_flag":40,"Type.type_name":100,"Type.type_name_en":100,"Type.type_name_es":100,"Customer.cust_doc":18,"Customer.cust_name":200} as const;
export type TYiiModelColumnSize = keyof typeof yiiModelColumnSizes;
function columnSize(name: TYiiModelColumnSize) { return yiiModelColumnSizes[name]; }
export default {attr, columnSize, name}
