<?php

namespace App\Enums;

enum YiiEnum: int
{
    // PHPGEN

    case STATUS_WAITING = 1;
    case STATUS_CANCELLED = 3;
    case STATUS_OK = 2;
    case PHONE_UNKNOWN_MOBILE = 1011;
    case PHONE_WORK = 1010;
    case PHONE_CONTACT = 1009;
    case PHONE_HOME = 1008;
    case FRAGEN_QUESTION_DATE = 1112;
    case FRAGEN_QUESTION_COMBO_BOX = 1114;
    case FRAGEN_QUESTION_CHECK_GROUP = 1101;
    case FRAGEN_QUESTION_RADIO_GROUP = 1102;
    case FRAGEN_QUESTION_TEXT_AREA = 1108;
    case FRAGEN_QUESTION_TEXT = 1107;
    case FRAGEN_QUESTION_CURRENCY = 1123;
    case FRAGEN_QUESTION_FLOAT = 1124;
    case FRAGEN_QUESTION_INTEGER = 1125;
    case FRAGEN_QUESTION_TEMPLATE = 1126;
    case FRAGEN_QUESTION_TEXT_PLAIN = 1127;
    case FRAGEN_QUESTION_TEXT_LIST = 1128;
    case FRAGEN_QUESTION_RADIO_TABLE = 1122;
    case FRAGEN_QUESTION_CHECK_TABLE = 1129;
    case FRAGEN_QUESTION_OPTION_DEFAULT = 6501;
    case FRAGEN_QUESTION_OPTION_OTHER = 6502;
    case FRAGEN_QUESTION_OPTION_DOES_NOT_APPLY = 6503;
    case FRAGEN_QUESTION_OPTION_NONE = 6504;
    case FRAGEN_QUESTION_OPTION_MALE = 6505;
    case FRAGEN_QUESTION_OPTION_FEMALE = 6506;
    case FRAGEN_QUESTION_OPTION_DO_NOT_KNOW = 6507;
    case FRAGEN_QUESTION_OPTION_SUM = 6508;
    case FRAGEN_QUESTION_OPTION_YES = 6511;
    case FRAGEN_QUESTION_OPTION_NO = 6512;
    case FRAGEN_QUESTION_OPTION_NOT_ANSWERED = 6513;
    case FRAGEN_QUESTION_OPTION_NOT_AVAILABLE = 6514;
    case FRAGEN_QUESTION_OPTION_DESCRIPTION = 6515;
    case FRAGEN_QUESTION_OPTION_TABLE_ROW = 6516;
    case FRAGEN_QUESTION_OPTION_TABLE_COL = 6517;
    case SURVEY_SEGMENT_EXC_CLO = 7001;
    case SURVEY_SEGMENT_EXC_CFO = 7002;
    case FILE_PROFILE_PHOTO = 2201;
    case FILE_DETACHED_FILE = 2251;
    case STORAGE_SERVICE_AWS_S3 = 4702;
    case STORAGE_SERVICE_DB = 4703;
    case STORAGE_SERVICE_FILE_SYSTEM = 4701;
    case STORAGE_SERVICE_CLOUDINARY = 4704;
    case STORAGE_DELIVERY_PUBLIC = 8001;
    case STORAGE_DELIVERY_PRIVATE = 8002;
    case STORAGE_DELIVERY_AUTHENTICATED = 8003;
    case GENDER_MALE = 401;
    case GENDER_FEMALE = 402;
    case USER_TOKEN_EMAIL_CHANGE = 8011;
    case USER_TOKEN_PASSWORD_RESET = 8012;
    case ROUTE_USER_RELATED = 213;
    case ROUTE_XHR = 214;
    case ROUTE_GRANTED = 211;
    case ROUTE_DEFAULT = 212;

    // PHPGEN
}
